### INITIAL PARAMETERS VALUES
GAMMA <- 1/6
R_MAX <- 4

F_MAX <- 1; F_MIN <- 0
BETA_MAX <- R_MAX * GAMMA
BETA_0 <- BETA_MAX * F_MAX

F_GENERAL <- 0.63; F_V <- 0.05
BETA <- (1-F_GENERAL) * BETA_0
BETA_V <- (1-F_V) * BETA_0

OMEGA <- 500
UPSILON <- 250
UPSILON_R <- UPSILON

KAPPA <- OMEGA

A_1 <- 0.9
A_2 <- A_1

D_FRACTION <- 0.1

T_MAX_INIT <- 2*365

### INITIAL POPULATION SIZE
S_INIT <- 100000
I_INIT <- 1
R_INIT <- 0
V_INIT <- 0